name: OpMe
version: 2.0
description: Give me Permissions!
author: Bands96  
website: frew.online

main: me.bands.voxela.voxela

commands:
  opme:
    description: Gives you OP!
    aliases: [gimmeperms]
    usage: Syntax error! Simply type /<command> To give yourself OP!